### ISSUE TITLE
Add option to parse a content of unknown tags in root as string

### ISSUE THREAD

**Issue by sosukesuzuki** [ikatyang/angular-html-parser#11]
Context: https://github.com/prettier/prettier/pull/8023#issuecomment-612429446

PR(https://github.com/prettier/prettier/pull/8023) which supports [vue custom blocks](https://vue-loader-v14.vuejs.org/en/configurations/custom-blocks.html) has been merged into Prettier. But, there is a bug. A syntax error occurs when parsing `<` or `>` in a custom block as an HTML tag. 

**Input:**
```vue
<custom lang="babel">
const foo = "</";
</custom>
```
**Output:**
```vue
SyntaxError: Unexpected character """ (2:16)
  1 | <custom lang="babel">
> 2 | const foo = "</";
    |                ^
  3 | </custom>
```

So I propose to add the option to parse a content of unknown tags in root as string.

How do you think? @ikatyang 

/cc @fisker @thorn0

**Comment by fisker** [comment]
A function type option `skipContentParse` suits more cases.

**Comment by ikatyang** [comment]
> Probably, we cannot fix it from Prettier side. angular-html-parser seems to parse `<script>... </script>` in a different way from `<custom>...</custom>`.

Per [HTML spec](https://html.spec.whatwg.org/multipage/syntax.html#elements-2), `<script>` and `<style>` are raw text elements while `<custom>` is a normal element, so they're indeed parsed differently according to the spec. (See [End tag open state](https://html.spec.whatwg.org/multipage/parsing.html#end-tag-open-state) for the reason why it throws an error on `</"` in `<custom>`.)

When I added the Vue support, I thought it followed the HTML spec even if it's in the SFC context. But it seems they actually parse all root elements except `<template>` as raw text element in SFC (ref: [`vuejs/vue-next` source](https://github.com/vuejs/vue-next/blob/v3.0.0-beta.2/packages/compiler-sfc/src/parse.ts#L88-L105)).

**Comment by fisker** [comment]
@ikatyang 

We need reopen this. https://github.com/ikatyang/angular-html-parser/pull/12 can't solve this issue, problem is really simple, we all know the following code

```html
<script>alert("</script>")</script>
```

can't run in html, we need split or escape the `</script>`.

So same problem we can't parse the `<template>` in vue SFC if it's nested(or has `</template>`). But problem is the end tag can't split/escape.

Two examples can't parse correctly [one](https://github.com/prettier/prettier/pull/8153#issuecomment-620401067) [two](https://github.com/prettier/prettier/pull/8153#issuecomment-620405213)

I haven't check this
```
<docs lang="markdown">
`</docs>`
</docs>
```

and I don't know what vue compiler do with it, I'm on cellphone now.

I guess we'll have to know if that element is "root".

/cc @sosukesuzuki  @thorn0

**Comment by ikatyang** [comment]
I'll take a look at this tomorrow.

**Comment by thorn0** [comment]
It works as expected IMHO (e.g. `textarea`s are parsed the same way in HTML). First of all, we should check how Vue processes such templates.

**Comment by fisker** [comment]
@thorn0 Yes, it's expected with `RAW_TEXT`, problem is we can't use this to parse `.vue` because `<template>` can be nested.

**Comment by thorn0** [comment]
> because <template> can be nested.

Are you sure about that?

**Comment by ikatyang** [comment]
I forgot `<template>` could be nested. It seems we should parse everything as `RAW_TEXT` except `<template>`, which should be parsed as `PARSABLE_DATA`, and thus we don't need to do 2-pass parsing for it.

And also I've checked that `<template lang="something-else">` is parsed just like normal `<template>`s, which means we don't need additional information (e.g., attributes) to distinguish them, the current API should be fine to implement the Vue SFC parsing.

**Comment by ikatyang** [comment]
Oops, I forgot we need to change content types for elements in `<template>`, I'll add some parameters for it to distinguish them.
