### ISSUE TITLE
Add attrs info for getTagContentType

### ISSUE THREAD

**Issue by ikatyang** [ikatyang/angular-html-parser#15]
Ref: https://github.com/vuejs/vue-next/issues/1120

It seems the `lang` attr is required for parsing Vue SFC.

cc @sosukesuzuki @fisker @thorn0

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/8153 Already got the attributes info?  [Prettier playground](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6IWArqdQHyVRYAUAbgLQCWAZlRABGQqkIAmagEpC8AM4wWqAPSZcBOIxAAaEBCwwe0OclB4ATuYgB3AAoWEJlHhzW8ATxO6ARubxgAazgYAGUsfx4yZBhzWjhdOAxvOAATFNSAGTwyWjxSOAAxCHMMAkMo51oYCB0QAAsYDBwAdTqeeXCwOBDHdp4OdvdkcDkvEEi5OHMYWz9SUuQ+F0ndACs5AA8AIT9A4JC8DDgMyLhF5fiQdY2QyNIcOABFWgh4c5wVmgtJ82GOONqWHMkRgzR4KRgdWQAA4AAy6IEQSbNPxYYZAuA-DhnXQARxe8Fm+icIDwci4UDgqVStXMcHxPDpszyCyQSw+l0mGB40VinLuD2erzObIuuhgeG8YIhUKQ4nFfh4ODuAGEIBhWSBMQBWWq0SYAFUlTnZn3+cAAklB0rAQmBgQYAILWkIwdwPd6TAC+XqAA)

**Comment by ikatyang** [comment]
- It uses an 2-pass approach to get the attrs info then do the parsing, where the first pass could be avoided if there are attrs info in `getTagContentType`. 
- Though it somehow works, the AST is not trustable if there are errors.

**Comment by ikatyang** [comment]
👉 https://github.com/ikatyang/angular-html-parser/releases/tag/v1.7.0
