### ISSUE TITLE
Arrow function syntax error in IE11 

### ISSUE THREAD

**Issue by jklotz** [ikatyang/angular-html-parser#18]
In IE11 this syntax error results from the use of an arrow function in the getParser function of the index.js file.
![image](https://user-images.githubusercontent.com/3790109/81589702-3e164d00-937f-11ea-8272-d984933456be.png)

![image](https://user-images.githubusercontent.com/3790109/81589793-63a35680-937f-11ea-87a9-2fc590d6f861.png)

**Angular Version:**
<pre><code>
Angular CLI: 8.3.19
Node: 10.16.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.0.6
@nguniversal/express-engine       7.1.1
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.3
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by ikatyang** [comment]
This package only supports `node@>=6`, you'll need to transpile it yourself if you want to use it in IE11.
