### ISSUE TITLE
Add full named entities support

### ISSUE THREAD

**Issue by Enuvid** [ikatyang/angular-html-parser#8]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
For now, a parser is not supporting all list of named entities, so we have errors in parsing completely correct (by WHATWG specification) data. Just because the parser side is not a complete list.

## Expected behavior
Anyway, there should be no mistake. There may be two solutions. We can update the list and bring it into line with the specification (for example, from [here](https://html.spec.whatwg.org/multipage/entities.json)). Or we can allow any sequence of characters between `&` and `;`.

### Input:

```html
<!DOCTYPE html>
<html>
<head>
<title>EXCL Entity Test</title>
</head>
<body>
<p>This is an exclamation entity: &excl;</p>
</body>
</html>
```

### Error:
```js
[
  {
    "span": {
      "start": {
        "file": {
          "content": "<!DOCTYPE html> <html> <head> <title>EXCL Entity Test</title> </head> <body> <p>This is an exclamation entity: &excl;</p> </body> </html>\n\n",
          "url": "angular-html-parser"
        },
        "offset": 111,
        "line": 0,
        "col": 111
      },
      "end": {
        "file": {
          "content": "<!DOCTYPE html> <html> <head> <title>EXCL Entity Test</title> </head> <body> <p>This is an exclamation entity: &excl;</p> </body> </html>\n\n",
          "url": "angular-html-parser"
        },
        "offset": 117,
        "line": 0,
        "col": 117
      },
      "details": null
    },
    "msg": "Unknown entity \"excl\" - use the \"&#<decimal>;\" or  \"&#x<hex>;\" syntax",
    "level": 1,
    "tokenType": 4
  }
]
```

## Environment

<pre><code>
Browser: all
 
For Tooling issues:
- Node version: all
- Platform:  all

Others:
</code></pre>

**Comment by ikatyang** [comment]
Hi, this looks like an issue for [`angular`](https://github.com/angular/angular) itself, `angular-html-parser` is simply a parser extracted from `angular` with some [modifications](https://github.com/ikatyang/angular-html-parser/tree/master/packages/angular-html-parser#modifications), you may have to open an issue there. Once it is supported in `angular`, we can simply sync the change from there to add support for it here.

**Comment by Enuvid** [comment]
This library is about html parser. It would be logical to have full syntax support.

In angular, the compiler used a shortlist of named entities, because this dictionary goes into production bundle and thereby minimize the size of the output bundle. From the point of view of the angular, this is quite correct.

But for html-parser, the witch used which is used in products like 'prettier', I think this is not correct.

**Comment by ikatyang** [comment]
Make sense.
